// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXzHV0DIOGyrTJmIM38uJyg4F6oVrvN7A',
    appId: '1:58375255369:web:a08e6c95202716c8ea1698',
    messagingSenderId: '58375255369',
    projectId: 'batch-17-1e534',
    authDomain: 'batch-17-1e534.firebaseapp.com',
    storageBucket: 'batch-17-1e534.firebasestorage.app',
    measurementId: 'G-B7SWHJE1WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAciB8ZLkVPACaHoKk2hdDc17AAd5iX43Y',
    appId: '1:58375255369:android:e8414dc593bee20aea1698',
    messagingSenderId: '58375255369',
    projectId: 'batch-17-1e534',
    storageBucket: 'batch-17-1e534.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhqm3-vDVPXMU0dLTHjTN3xsTX50aU2Jc',
    appId: '1:58375255369:ios:f6ae5bdae603a6bcea1698',
    messagingSenderId: '58375255369',
    projectId: 'batch-17-1e534',
    storageBucket: 'batch-17-1e534.firebasestorage.app',
    iosBundleId: 'com.example.batch17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhqm3-vDVPXMU0dLTHjTN3xsTX50aU2Jc',
    appId: '1:58375255369:ios:f6ae5bdae603a6bcea1698',
    messagingSenderId: '58375255369',
    projectId: 'batch-17-1e534',
    storageBucket: 'batch-17-1e534.firebasestorage.app',
    iosBundleId: 'com.example.batch17',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXzHV0DIOGyrTJmIM38uJyg4F6oVrvN7A',
    appId: '1:58375255369:web:de93d0a65e441cd2ea1698',
    messagingSenderId: '58375255369',
    projectId: 'batch-17-1e534',
    authDomain: 'batch-17-1e534.firebaseapp.com',
    storageBucket: 'batch-17-1e534.firebasestorage.app',
    measurementId: 'G-51XDXWEXYM',
  );
}
